name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev using `flutter pub publish`.
# This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # --- Tambahan dari proyek kamu ---
  app_links: ^3.5.0 
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

  flutter_localizations:
    sdk: flutter
  intl: any  

  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.2.0
  flutter_local_notifications: ^17.2.3

  image_picker: ^1.1.1
  image: ^4.2.0
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0

  banner_carousel: ^1.2.1
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  share_plus: ^7.2.1
  http: ^1.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration for the flutter_launcher_icons package.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Primez Sports.jpg"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see:
# https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
