name: my_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Dasar UI & Styling ---
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

  # --- State Management & Routing ---
  provider: ^6.1.5
  go_router: ^16.1.0

  # --- Firebase & Notifikasi ---
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  flutter_local_notifications: ^19.5.0
  firebase_app_check: ^0.4.1+2

  # --- Gambar & ML Kit ---
  image_picker: ^1.1.1
  image: ^4.5.4
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0

  # --- Utilitas & Jaringan ---
  http: ^1.2.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  app_links: ^6.4.1
  
  # --- UI Components ---
  smooth_page_indicator: ^1.1.0
  banner_carousel: ^1.2.1
  readmore: ^2.2.0

  # --- Storage & Cache ---
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.5.3

  # --- Internasionalisasi ---
  flutter_localizations:
    sdk: flutter
  intl: any
  timeago: ^3.6.0

  # --- Backend ---
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Primez_Sports.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Primez_Sports.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
